apiVersion: sre.platform.ohanyere.io/v1alpha1
kind: ServiceLevelObjective
metadata:
  name: receipt-api-availability
  labels:
    app.kubernetes.io/name: receipt-api
    finops.ohanyere.io/cost-center: commerce
spec:
  service: receipt-api
  owner: Commerce
  objective: 99.9
  window: 30d
  indicator:
    type: availability
    goodEvents: sum(rate(http_requests_total{service="receipt-api",status!~"5.."}[5m]))
    totalEvents: sum(rate(http_requests_total{service="receipt-api"}[5m]))
  alerting:
    burnRate:
      enabled: true
