apiVersion: storage.platform.ohanyere.io/v1alpha1
kind: S3BucketClaim
metadata:
  name: receipt-api-bucket
  labels:
    app.kubernetes.io/name: receipt-api
    finops.ohanyere.io/cost-center: commerce
spec:
  environment: dev
  versioning: true
  encryption: platform-managed
  lifecycle:
    transitionToInfrequentAccessDays: 30
