apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: receipt-api
  labels:
    app.kubernetes.io/name: receipt-api
subjects:
  - kind: ServiceAccount
    name: receipt-api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: receipt-api
